spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentmanagament
    username: root
    password: 0993337423A@a
    driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    port: 8080
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

